version: '3.2'

services:

  # Workers
  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis
      - mongo

  # Twiiter subscriber
  sub:
    build: 
      context: .
      dockerfile: docker/sub.Dockerfile
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis
      - mongo

  # Extra services
  redis:
    image: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"