version: '3.2'

services:
  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    links:
      - redis
    depends_on:
      - redis

  sub:
    build: 
      context: .
      dockerfile: docker/sub.Dockerfile
    env_file:
      - .env
    ports:
      - "5566:5566"
      - "4444:4444"
    links:
      - redis
    depends_on:
      - redis

  redis:
    hostname: redis
    image: redis:latest
    volumes:
      - /docker/redis-data:/data
    ports:
      - "6379:6379"
