version: '3.2'

services:
  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis

  sub:
    build: 
      context: .
      dockerfile: docker/sub.Dockerfile
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: redis
    # volumes:
    #   - /Users:/twitter
    ports:
      - 6379:6379