import os
import tweepy

TWITTER_ACCESS_TOKEN = os.environ.get("TWITTER_ACCESS_TOKEN")
TWITTER_ACCESS_SECRET_TOKEN = os.environ.get("TWITTER_ACCESS_SECRET_TOKEN")
TWITTER_CONSUMER_API_KEY = os.environ.get("TWITTER_CONSUMER_API_KEY")
TWITTER_CONSUMER_API_SECRET_KEY = os.environ.get(
    "TWITTER_CONSUMER_API_SECRET_KEY")


# Authentification
_auth = tweepy.OAuthHandler(
    TWITTER_CONSUMER_API_KEY,
    TWITTER_CONSUMER_API_SECRET_KEY)


_auth.set_access_token(
    TWITTER_ACCESS_TOKEN,
    TWITTER_ACCESS_SECRET_TOKEN)

api = tweepy.API(_auth)
